DROP VIEW IF EXISTS subcategories_main;
DROP VIEW IF EXISTS subcategories_thread_counts;
DROP VIEW IF EXISTS users_post_counts;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS subcategories;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS groups;
